/*
- Create the donations table according to schema described
- Write RLS (row level security) policies following supabase/schemas/example.sql 
that enable unauthenticated users to view/update the table
*/

create table donations (
    donation_id uuid default uuid_generate_v4() primary key, -- generated by default
    receiver_user_id uuid not null references users(id), -- linked to users table, required
    store_id uuid references stores(id), -- linked to stores table, optional
    date_submitted timestamp with time zone default current_timestamp, -- generated by default
    donor_is_individual boolean not null, -- optional, used if donor is an individual
    donor_individual_name text, -- optional, used if donor is an individual
    donor_business_name text, -- optional, used if donor is a business
    donor_business_contact_name text, -- optional, used if donor is a business
    donor_email varchar(255), -- optional, can't store more than 255 characters
    donor_phone varchar(20), -- optional, can't store more than 20 characters
    donor_street_address boolean not null, -- required, whether or not donor wants to receive mailings
    donor_receive_mailings boolean not null, -- required, whether or not donor wants to receive mailings
    donor_receive_emails boolean not null, -- required, whether or not donor wants to receive emails
    donor_remain_anonymous boolean not null, -- required, whether or not donor wants to remain anonymous
    estimated_value numeric not null, -- required, estimated value of donation in USD
    items_donated text not null -- required, free-text description of items
);